/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in many projects. It is checked in here so
// the empty repository has stable TypeScript references from the first commit.
